spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 732029033372-g7dvhlepi93l4s9pr6ma8ehmdsi92ife.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          naver:
            client-name: Naver
            client-id: kH1o7aq3SwqD8pz10Rdp
            client-secret: njcZ9x1xqJ
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            #            client-authentication-method: client_secret_post
            scope:
              - name
              - email
          kakao:
            client-id: fedfbc51e173ad86179217f6a28b46e0
            client-secret: VMPtLor855hlbfOAtzuFIOgoTTg3rkwG
            scope:
              - profile_nickname
              - profile_image
              - account_email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-name: kakao
            client-authentication-method: client_secret_post

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: testuser
    password: testpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # ?? none, create, create-drop, validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: ajvnkjafnvofdnvasvnasvnlasvnlvnafslvnlanvlkfasvnlkafvnlkfvniavnsvasvnaslvnaslvkansdlnaslasdklmasdlk
  expiration: 3600000 # 1 hour
  refresh:
    expiration: 604800000 # 7 days

chat-gpt:
  key: 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